from dkundel/sslaunch

RUN apt-get install -y python-pip


WORKDIR /sdk-starter-kits/python

RUN echo "Downloading SDK Starter Python"
RUN wget -O python.zip "https://github.com/TwilioDevEd/sdk-starter-python/archive/master.zip"

RUN echo "Unzipping SDK Starter Python"
RUN unzip python.zip
RUN rm python.zip

WORKDIR /sdk-starter-kits/python/sdk-starter-python-master
RUN ls -l
RUN cp .env.example .env

EXPOSE 5000
RUN pip install -r requirements.txt

CMD ["python", "app.py"]